CREATE TABLE ADM_TIPO_REPORTE (
   ID_TIPO_REPORTE      VARCHAR(50)          NOT NULL,
   DESCRIPCION          VARCHAR(100)         NULL,
   VIGENTE              BIT                  NULL,
   CONSTRAINT PK_ADM_TIPO_REPORTE PRIMARY KEY (ID_TIPO_REPORTE)
)
GO

CREATE TABLE ADM_REPORTE (
   ID_REPORTE           VARCHAR(30)          NOT NULL,
   ID_TIPO_REPORTE      VARCHAR(50)          NULL,
   NOMBRE_REPORTE       VARCHAR(100)         NULL,
   VIGENTE              BIT                  NULL,
   CONSTRAINT PK_ADM_REPORTE PRIMARY KEY (ID_REPORTE)
)
GO

ALTER TABLE ADM_REPORTE
   ADD CONSTRAINT FK_ADM_REPORTE_TIPO FOREIGN KEY (ID_TIPO_REPORTE)
      REFERENCES ADM_TIPO_REPORTE (ID_TIPO_REPORTE)
         ON UPDATE CASCADE
GO

CREATE TABLE ADM_ELEMENTO_REPORTE_AYUDA (
   ID_ELEMENTO          INT                  NOT NULL,
   ID_REPORTE           VARCHAR(30)          NOT NULL,
   NOMBRE               VARCHAR(50)          NULL,
   TEXTO_AYUDA          TEXT                 NULL,
   CONSTRAINT PK_ADM_ELEMENTO_REPORTE_AYUDA PRIMARY KEY (ID_ELEMENTO, ID_REPORTE)
)
GO

ALTER TABLE ADM_ELEMENTO_REPORTE_AYUDA
   ADD CONSTRAINT FK_REPORTE_ELEMENTOS FOREIGN KEY (ID_REPORTE)
      REFERENCES ADM_REPORTE (ID_REPORTE)
         ON UPDATE CASCADE
GO