

CREATE PROCEDURE pa_ADM_ELEMENTO_REPORTE_AYUDA_Sel(@id_reporte VARCHAR(30))
AS
BEGIN
	SELECT aera.NOMBRE
	      ,aera.TEXTO_AYUDA
	FROM   ADM_ELEMENTO_REPORTE_AYUDA AS aera
	WHERE  aera.ID_REPORTE = @id_reporte
	ORDER BY
	       aera.ID_ELEMENTO
END
